@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImVjYWQ0YjU1LTE1YjQtNDRlNS1hMTY5LTVhYmZiYmU2NmI4OSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2OTMxMzA5MSwiZXhwIjoxNjY5MzEzNjkxfQ.e5s4wbjb8RaxEhU7aHPFX5d1WsfPoh7QAKXd1fpHr30


### Cadastro
POST http://localhost:3003/user/signup 
Content-Type: application/json

{
   "name":"Lunnaa", 
   "email":"lunna@gmail.com", 
   "password":"123456", 
   "role":"ADMIN"
}


### Login
POST http://localhost:3003/user/login 
Content-Type: application/json

{
   "email": "lunna@gmail.com", 
   "password":"123456"
}

###  Registrar banda
POST http://localhost:3003/band/add 
Authorization: {{token}}
Content-Type: application/json

{
   "name": "A maior saudade", 
   "music_genre": "Sertanejo", 
   "responsible": "H e J"
}


### DETALHES DAS BANDAS
GET http://localhost:3003/band/b941b81b-b5a8-4ce9-a4b0-d3635555d3b5
Authorization: {{token}}

###MOSTRAR TODOS OS SHOW DE UM DIA
GET http://localhost:3003/show/getshow/?week_day=domingo
Authorization: {{token}}

### ADICIONAR LISTA DE SHOWS
POST http://localhost:3003/show/create 
Authorization: {{token}}
Content-Type: application/json 

{
   "band_id": "b941b81b-b5a8-4ce9-a4b0-d3635555d3b5", "week_day": "domingo", 
   "start_time": 12, 
   "end_time": 13
}

